require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnnouncementsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Announcement. As you add validations to Announcement, be sure to
  # adjust the attributes here as well.
  let(:user) { FactoryGirl.create(:user) }

  let(:valid_attributes) {
    {
      user_id: user.id,
      restaurant_name: "Bangkok Taste"
    }
  }

  before(:each) { sign_in(user) }

  let(:default_params) { { format: :json } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnnouncementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all announcements as @announcements" do
      announcement = Announcement.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:announcements)).to eq([announcement])
    end
  end

  describe "GET show" do
    it "assigns the requested announcement as @announcement" do
      announcement = Announcement.create! valid_attributes
      get :show, {:id => announcement.to_param}, valid_session
      expect(assigns(:announcement)).to eq(announcement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Announcement" do
        expect {
          post :create, {:announcement => valid_attributes}, valid_session
        }.to change(Announcement, :count).by(1)
      end

      it "assigns a newly created announcement as @announcement" do
        post :create, {:announcement => valid_attributes}, valid_session
        expect(assigns(:announcement)).to be_a(Announcement)
        expect(assigns(:announcement)).to be_persisted
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved announcement as @announcement" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Announcement).to receive(:save).and_return(false)
        post :create, {:announcement => { "user_id" => "invalid value" }}, valid_session
        expect(assigns(:announcement)).to be_a_new(Announcement)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested announcement" do
        announcement = Announcement.create! valid_attributes
        # Assuming there are no other announcement in the database, this
        # specifies that the Announcement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Announcement).to receive(:update).with({ "restaurant_name" => "foo" })
        put :update, {:id => announcement.id, :announcement => { "restaurant_name" => "foo" }}, valid_session
      end

      it "assigns the requested announcement as @announcement" do
        announcement = Announcement.create! valid_attributes
        put :update, {:id => announcement.to_param, :announcement => valid_attributes}, valid_session
        expect(assigns(:announcement)).to eq(announcement)
      end
    end

    describe "with invalid params" do
      it "assigns the announcement as @announcement" do
        announcement = Announcement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Announcement).to receive(:save).and_return(false)
        put :update, {:id => announcement.to_param, :announcement => { "user" => "invalid value" }}, valid_session
        expect(assigns(:announcement)).to eq(announcement)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested announcement" do
      announcement = Announcement.create! valid_attributes
      expect {
        delete :destroy, {:id => announcement.to_param}, valid_session
      }.to change(Announcement, :count).by(-1)
    end
  end

end
