require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProspectiveUsersController do

  before(:each) { sign_in nil }

  # This should return the minimal set of attributes required to create a valid
  # ProspectiveUser. As you add validations to ProspectiveUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "first_name" => "MyString", "email" => "john.smith@example.com" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProspectiveUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET new" do
    it "assigns a new prospective_user as @prospective_user" do
      get :new, {}, valid_session
      assigns(:prospective_user).should be_a_new(ProspectiveUser)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProspectiveUser" do
        expect {
          post :create, {:prospective_user => valid_attributes}, valid_session
        }.to change(ProspectiveUser, :count).by(1)
      end

      it "assigns a newly created prospective_user as @prospective_user" do
        post :create, {:prospective_user => valid_attributes}, valid_session
        assigns(:prospective_user).should be_a(ProspectiveUser)
        assigns(:prospective_user).should be_persisted
      end

      it "redirects to the thanks page" do
        post :create, {:prospective_user => valid_attributes}, valid_session
        response.should redirect_to(thanks_prospective_users_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prospective_user as @prospective_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveUser.any_instance.stub(:save).and_return(false)
        post :create, {:prospective_user => { "first_name" => "invalid value" }}, valid_session
        assigns(:prospective_user).should be_a_new(ProspectiveUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveUser.any_instance.stub(:save).and_return(false)
        post :create, {:prospective_user => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end
end
