require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProspectiveUsersController do

  # This should return the minimal set of attributes required to create a valid
  # ProspectiveUser. As you add validations to ProspectiveUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "first_name" => "MyString", "email" => "john.smith@example.com" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProspectiveUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all prospective_users as @prospective_users" do
      prospective_user = ProspectiveUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prospective_users).should eq([prospective_user])
    end
  end

  describe "GET show" do
    it "assigns the requested prospective_user as @prospective_user" do
      prospective_user = ProspectiveUser.create! valid_attributes
      get :show, {:id => prospective_user.to_param}, valid_session
      assigns(:prospective_user).should eq(prospective_user)
    end
  end

  describe "GET new" do
    it "assigns a new prospective_user as @prospective_user" do
      get :new, {}, valid_session
      assigns(:prospective_user).should be_a_new(ProspectiveUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested prospective_user as @prospective_user" do
      prospective_user = ProspectiveUser.create! valid_attributes
      get :edit, {:id => prospective_user.to_param}, valid_session
      assigns(:prospective_user).should eq(prospective_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProspectiveUser" do
        expect {
          post :create, {:prospective_user => valid_attributes}, valid_session
        }.to change(ProspectiveUser, :count).by(1)
      end

      it "assigns a newly created prospective_user as @prospective_user" do
        post :create, {:prospective_user => valid_attributes}, valid_session
        assigns(:prospective_user).should be_a(ProspectiveUser)
        assigns(:prospective_user).should be_persisted
      end

      it "redirects to the created prospective_user" do
        post :create, {:prospective_user => valid_attributes}, valid_session
        response.should redirect_to(ProspectiveUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prospective_user as @prospective_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveUser.any_instance.stub(:save).and_return(false)
        post :create, {:prospective_user => { "first_name" => "invalid value" }}, valid_session
        assigns(:prospective_user).should be_a_new(ProspectiveUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveUser.any_instance.stub(:save).and_return(false)
        post :create, {:prospective_user => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prospective_user" do
        prospective_user = ProspectiveUser.create! valid_attributes
        # Assuming there are no other prospective_user in the database, this
        # specifies that the ProspectiveUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProspectiveUser.any_instance.should_receive(:update).with({ "first_name" => "MyString" })
        put :update, {:id => prospective_user.to_param, :prospective_user => { "first_name" => "MyString" }}, valid_session
      end

      it "assigns the requested prospective_user as @prospective_user" do
        prospective_user = ProspectiveUser.create! valid_attributes
        put :update, {:id => prospective_user.to_param, :prospective_user => valid_attributes}, valid_session
        assigns(:prospective_user).should eq(prospective_user)
      end

      it "redirects to the prospective_user" do
        prospective_user = ProspectiveUser.create! valid_attributes
        put :update, {:id => prospective_user.to_param, :prospective_user => valid_attributes}, valid_session
        response.should redirect_to(prospective_user)
      end
    end

    describe "with invalid params" do
      it "assigns the prospective_user as @prospective_user" do
        prospective_user = ProspectiveUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => prospective_user.to_param, :prospective_user => { "first_name" => "invalid value" }}, valid_session
        assigns(:prospective_user).should eq(prospective_user)
      end

      it "re-renders the 'edit' template" do
        prospective_user = ProspectiveUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => prospective_user.to_param, :prospective_user => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prospective_user" do
      prospective_user = ProspectiveUser.create! valid_attributes
      expect {
        delete :destroy, {:id => prospective_user.to_param}, valid_session
      }.to change(ProspectiveUser, :count).by(-1)
    end

    it "redirects to the prospective_user list" do
      prospective_user = ProspectiveUser.create! valid_attributes
      delete :destroy, {:id => prospective_user.to_param}, valid_session
      response.should redirect_to(prospective_users_url)
    end
  end

end
